# Jaesung Choi (jc13152)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-app
  template:
    metadata:
      labels:
        app: us-app
    spec:
      containers:
      - name: us-container
        image: docker.io/jasonnyu/us-image:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: us-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      nodePort: 30003
  selector:
    app: us-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-app
  template:
    metadata:
      labels:
        app: fs-app
    spec:
      containers:
      - name: fs-container
        image: docker.io/jasonnyu/fs-image:latest
        ports:
        - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      nodePort: 30002
  selector:
    app: fs-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-app
  template:
    metadata:
      labels:
        app: as-app
    spec:
      containers:
      - name: as-container
        image: docker.io/jasonnyu/as-image:latest
        ports:
        - containerPort: 53533

---

apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  type: LoadBalancer
  ports:
    - port: 53533
      nodePort: 30001
      protocol: UDP  
  selector:
    app: as-app
